### ISSUE TITLE
[Metal] ASN fields should be uint32 (or int64 for OAS3 compatibility)

### ISSUE THREAD

**Issue by displague** [equinix/equinix-sdk-go#41]
All ASN fields (`peer_as`, `origin_as` (below), `peer_asn`, `local_asn`, `asn`, `bgp_neighbor_asn`) should be updated to int64 with a `min:0` and `max:2^32` (since there is no uint32 type in OAS3).

* https://spec.openapis.org/oas/v3.0.3#data-types
* https://www.arin.net/resources/guide/asn/#:~:text=A%204%2Dbyte%20ASN%20is,to

**Comment by lennardk** [comment]
If I interpret things correctly, the api has been updated. Does this mean the SDK can now be updated to match the API?

**Comment by lennardk** [comment]
@displague is this something you can help moving forward?

**Comment by displague** [comment]
Closing. https://github.com/equinix/equinix-sdk-go/pull/57/commits/9504c5bd70ac1a62470e9f3e33d0c249e6787427 was included in #57, released as v0.39.0
